services:
  qbittorrent-completed-remover:
    restart: unless-stopped
    image: ghcr.io/milanmdev/qbittorrent-completed-remover
    environment:
      - USERNAME=admin
      - PASSWORD=adminadmin
      - CLIENT=http://127.0.0.1:8080